In [1]:
import numpy as np

# First-Order Differences Gradient

In [2]:
numpy_array = np.array([1, 2, 4, 7, 11, 16], dtype=float)
np.gradient(numpy_array)

array([1. , 1.5, 2.5, 3.5, 4.5, 5. ])

# Second-Order Differences Gradient

In [3]:
np.gradient(numpy_array, 2)

array([0.5 , 0.75, 1.25, 1.75, 2.25, 2.5 ])

# Gradient of Multiple Arrays

In [4]:
numpy_array2 = np.array([2, 1, 5, 10, 11, 15], dtype=float)
np.gradient(numpy_array, numpy_array2)

array([-1.        , -1.5       ,  0.54444444,  3.43333333,  3.45      ,
        1.25      ])

# Gradient for the N-Dimensional Numpy Array

In [6]:
numpy_array_2d = np.array([[10, 20, 30], [40, 50, 60]], dtype=float)
np.gradient(numpy_array_2d)

[array([[30., 30., 30.],
        [30., 30., 30.]]),
 array([[10., 10., 10.],
        [10., 10., 10.]])]

# Numpy Gradient of a Function

In [8]:
import numdifftools as nd

In [9]:
def f1(x):
    return x**2 + 1
grad = nd.Gradient(f1)([1])
grad

array(2.)